### PR TITLE
DSDT.asl

### PR DESCRIPTION
**Pull request by yuweiyuan8**
DSDT.asl on redmi k30pro

### CODE REVIEW

**Comment by Robotix22** [comment]
From where is the ACPI Source?

**Comment by N1kroks** [comment]
> From where is the ACPI Source?

Like port it's just a copy-paste alioth

**Comment by Robotix22** [comment]
That dosen't sound Good, Or is it?

**Comment by N1kroks** [comment]
Yeah well that's not good

**Comment by Robotix22** [comment]
Alright, Closing Pull Request then

**Pull request closed without merging**
